// Mocks generated by Mockito 5.4.0 from annotations
// in student_marketplace_presentation/test/core/entities.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:student_marketplace_business_logic/domain/entities/product_category_entity.dart'
    as _i2;
import 'package:student_marketplace_business_logic/domain/entities/sale_post_entity.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductCategoryEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductCategoryEntity extends _i1.Mock
    implements _i2.ProductCategoryEntity {
  MockProductCategoryEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: 0,
      ) as int);
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: '',
      ) as String);
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}

/// A class which mocks [SalePostEntity].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalePostEntity extends _i1.Mock implements _i3.SalePostEntity {
  MockSalePostEntity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get price => (super.noSuchMethod(
        Invocation.getter(#price),
        returnValue: '',
      ) as String);
  @override
  set price(String? _price) => super.noSuchMethod(
        Invocation.setter(
          #price,
          _price,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get title => (super.noSuchMethod(
        Invocation.getter(#title),
        returnValue: '',
      ) as String);
  @override
  set title(String? _title) => super.noSuchMethod(
        Invocation.setter(
          #title,
          _title,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<_i4.Uint8List> get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: <_i4.Uint8List>[],
      ) as List<_i4.Uint8List>);
  @override
  set postId(int? _postId) => super.noSuchMethod(
        Invocation.setter(
          #postId,
          _postId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set ownerId(int? _ownerId) => super.noSuchMethod(
        Invocation.setter(
          #ownerId,
          _ownerId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set categoryId(int? _categoryId) => super.noSuchMethod(
        Invocation.setter(
          #categoryId,
          _categoryId,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set description(String? _description) => super.noSuchMethod(
        Invocation.setter(
          #description,
          _description,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set postingDate(String? _postingDate) => super.noSuchMethod(
        Invocation.setter(
          #postingDate,
          _postingDate,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set ownerName(String? _ownerName) => super.noSuchMethod(
        Invocation.setter(
          #ownerName,
          _ownerName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set categoryName(String? _categoryName) => super.noSuchMethod(
        Invocation.setter(
          #categoryName,
          _categoryName,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set isFavorite(bool? _isFavorite) => super.noSuchMethod(
        Invocation.setter(
          #isFavorite,
          _isFavorite,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set isOwn(bool? _isOwn) => super.noSuchMethod(
        Invocation.setter(
          #isOwn,
          _isOwn,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set viewsCount(int? _viewsCount) => super.noSuchMethod(
        Invocation.setter(
          #viewsCount,
          _viewsCount,
        ),
        returnValueForMissingStub: null,
      );
  @override
  List<Object?> get props => (super.noSuchMethod(
        Invocation.getter(#props),
        returnValue: <Object?>[],
      ) as List<Object?>);
}
