// Mocks generated by Mockito 5.4.0 from annotations
// in student_marketplace_presentation/test/core/usecase.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:student_marketplace_business_logic/core/error/failures.dart'
    as _i10;
import 'package:student_marketplace_business_logic/core/usecase/usecase.dart'
    as _i12;
import 'package:student_marketplace_business_logic/domain/entities/auth_session_entity.dart'
    as _i19;
import 'package:student_marketplace_business_logic/domain/entities/product_category_entity.dart'
    as _i17;
import 'package:student_marketplace_business_logic/domain/entities/sale_post_entity.dart'
    as _i14;
import 'package:student_marketplace_business_logic/domain/entities/user_entity.dart'
    as _i11;
import 'package:student_marketplace_business_logic/domain/operations/sale_post_operations.dart'
    as _i7;
import 'package:student_marketplace_business_logic/domain/repositories/auth_session_repository.dart'
    as _i3;
import 'package:student_marketplace_business_logic/domain/repositories/product_category_repository.dart'
    as _i6;
import 'package:student_marketplace_business_logic/domain/repositories/sale_post_repository.dart'
    as _i5;
import 'package:student_marketplace_business_logic/domain/repositories/user_repository.dart'
    as _i2;
import 'package:student_marketplace_business_logic/domain/usecases/authentication/get_cached_session_usecase.dart'
    as _i18;
import 'package:student_marketplace_business_logic/domain/usecases/product_category/get_all_categories_usecase.dart'
    as _i16;
import 'package:student_marketplace_business_logic/domain/usecases/sale_post/add_to_favorites_usecase.dart'
    as _i21;
import 'package:student_marketplace_business_logic/domain/usecases/sale_post/get_all_posts_by_category_usecase.dart'
    as _i15;
import 'package:student_marketplace_business_logic/domain/usecases/sale_post/get_all_posts_by_query_usecase.dart'
    as _i22;
import 'package:student_marketplace_business_logic/domain/usecases/sale_post/get_all_posts_usecase.dart'
    as _i13;
import 'package:student_marketplace_business_logic/domain/usecases/sale_post/get_detailed_post_usecase.dart'
    as _i20;
import 'package:student_marketplace_business_logic/domain/usecases/sale_post/remove_from_favorites_usecase.dart'
    as _i23;
import 'package:student_marketplace_business_logic/domain/usecases/user/get_user_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthSessionRepository_1 extends _i1.SmartFake
    implements _i3.AuthSessionRepository {
  _FakeAuthSessionRepository_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalePostRepository_3 extends _i1.SmartFake
    implements _i5.SalePostRepository {
  _FakeSalePostRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProductCategoryRepository_4 extends _i1.SmartFake
    implements _i6.ProductCategoryRepository {
  _FakeProductCategoryRepository_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSalePostOperations_5 extends _i1.SmartFake
    implements _i7.SalePostOperations {
  _FakeSalePostOperations_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserProfileUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUsecase extends _i1.Mock
    implements _i8.GetUserProfileUsecase {
  MockGetUserProfileUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get userRepository => (super.noSuchMethod(
        Invocation.getter(#userRepository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#userRepository),
        ),
      ) as _i2.UserRepository);
  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, _i11.UserEntity>> call(
          _i12.OptionalIdParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i9.Future<_i4.Either<_i10.Failure, _i11.UserEntity>>.value(
                _FakeEither_2<_i10.Failure, _i11.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, _i11.UserEntity>>);
}

/// A class which mocks [GetAllPostsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPostsUsecase extends _i1.Mock
    implements _i13.GetAllPostsUsecase {
  MockGetAllPostsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SalePostRepository get postRepository => (super.noSuchMethod(
        Invocation.getter(#postRepository),
        returnValue: _FakeSalePostRepository_3(
          this,
          Invocation.getter(#postRepository),
        ),
      ) as _i5.SalePostRepository);
  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, List<_i14.SalePostEntity>>> call(
          _i12.LimitOffsetParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i4.Either<_i10.Failure, List<_i14.SalePostEntity>>>.value(
            _FakeEither_2<_i10.Failure, List<_i14.SalePostEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, List<_i14.SalePostEntity>>>);
}

/// A class which mocks [GetAllPostsByCategoryUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPostsByCategoryUsecase extends _i1.Mock
    implements _i15.GetAllPostsByCategoryUsecase {
  MockGetAllPostsByCategoryUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SalePostRepository get postRepository => (super.noSuchMethod(
        Invocation.getter(#postRepository),
        returnValue: _FakeSalePostRepository_3(
          this,
          Invocation.getter(#postRepository),
        ),
      ) as _i5.SalePostRepository);
  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, List<_i14.SalePostEntity>>> call(
          _i12.CategoryParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i4.Either<_i10.Failure, List<_i14.SalePostEntity>>>.value(
            _FakeEither_2<_i10.Failure, List<_i14.SalePostEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, List<_i14.SalePostEntity>>>);
}

/// A class which mocks [GetAllCategoriesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesUsecase extends _i1.Mock
    implements _i16.GetAllCategoriesUsecase {
  MockGetAllCategoriesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.ProductCategoryRepository get categoryRepository => (super.noSuchMethod(
        Invocation.getter(#categoryRepository),
        returnValue: _FakeProductCategoryRepository_4(
          this,
          Invocation.getter(#categoryRepository),
        ),
      ) as _i6.ProductCategoryRepository);
  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, List<_i17.ProductCategoryEntity>>> call(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i4.Either<_i10.Failure,
                    List<_i17.ProductCategoryEntity>>>.value(
            _FakeEither_2<_i10.Failure, List<_i17.ProductCategoryEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9
          .Future<_i4.Either<_i10.Failure, List<_i17.ProductCategoryEntity>>>);
}

/// A class which mocks [GetCachedSessionUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCachedSessionUsecase extends _i1.Mock
    implements _i18.GetCachedSessionUsecase {
  MockGetCachedSessionUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthSessionRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, _i19.AuthSessionEntity>> call(
          _i12.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i9.Future<_i4.Either<_i10.Failure, _i19.AuthSessionEntity>>.value(
                _FakeEither_2<_i10.Failure, _i19.AuthSessionEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, _i19.AuthSessionEntity>>);
}

/// A class which mocks [GetDetailedPostUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailedPostUsecase extends _i1.Mock
    implements _i20.GetDetailedPostUsecase {
  MockGetDetailedPostUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SalePostRepository get postRepository => (super.noSuchMethod(
        Invocation.getter(#postRepository),
        returnValue: _FakeSalePostRepository_3(
          this,
          Invocation.getter(#postRepository),
        ),
      ) as _i5.SalePostRepository);
  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, _i14.SalePostEntity>> call(
          _i12.IdParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i9.Future<_i4.Either<_i10.Failure, _i14.SalePostEntity>>.value(
                _FakeEither_2<_i10.Failure, _i14.SalePostEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, _i14.SalePostEntity>>);
}

/// A class which mocks [AddToFavoritesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddToFavoritesUsecase extends _i1.Mock
    implements _i21.AddToFavoritesUsecase {
  MockAddToFavoritesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i7.SalePostOperations get salePostOperations => (super.noSuchMethod(
        Invocation.getter(#salePostOperations),
        returnValue: _FakeSalePostOperations_5(
          this,
          Invocation.getter(#salePostOperations),
        ),
      ) as _i7.SalePostOperations);
  @override
  _i9.Future<_i4.Either<_i10.Failure, bool>> call(_i12.IdParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<_i4.Either<_i10.Failure, bool>>.value(
            _FakeEither_2<_i10.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, bool>>);
}

/// A class which mocks [GetAllPostsByQueryUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllPostsByQueryUsecase extends _i1.Mock
    implements _i22.GetAllPostsByQueryUsecase {
  MockGetAllPostsByQueryUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SalePostRepository get postRepository => (super.noSuchMethod(
        Invocation.getter(#postRepository),
        returnValue: _FakeSalePostRepository_3(
          this,
          Invocation.getter(#postRepository),
        ),
      ) as _i5.SalePostRepository);
  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i9.Future<_i4.Either<_i10.Failure, List<_i14.SalePostEntity>>> call(
          _i12.QueryParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<
                _i4.Either<_i10.Failure, List<_i14.SalePostEntity>>>.value(
            _FakeEither_2<_i10.Failure, List<_i14.SalePostEntity>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, List<_i14.SalePostEntity>>>);
}

/// A class which mocks [RemoveFromFavoritesUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFromFavoritesUsecase extends _i1.Mock
    implements _i23.RemoveFromFavoritesUsecase {
  MockRemoveFromFavoritesUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthSessionRepository get authRepository => (super.noSuchMethod(
        Invocation.getter(#authRepository),
        returnValue: _FakeAuthSessionRepository_1(
          this,
          Invocation.getter(#authRepository),
        ),
      ) as _i3.AuthSessionRepository);
  @override
  _i7.SalePostOperations get salePostOperations => (super.noSuchMethod(
        Invocation.getter(#salePostOperations),
        returnValue: _FakeSalePostOperations_5(
          this,
          Invocation.getter(#salePostOperations),
        ),
      ) as _i7.SalePostOperations);
  @override
  _i9.Future<_i4.Either<_i10.Failure, bool>> call(_i12.IdParam? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i9.Future<_i4.Either<_i10.Failure, bool>>.value(
            _FakeEither_2<_i10.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i9.Future<_i4.Either<_i10.Failure, bool>>);
}
