// Mocks generated by Mockito 5.3.2 from annotations
// in student_marketplace_frontend/test/domain/usecases/authentication_credentials/check_email_availability_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:student_marketplace_frontend/core/error/failures.dart' as _i5;
import 'package:student_marketplace_frontend/domain/repositories/user/authentication_credentials_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationCredentialsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationCredentialsRepository extends _i1.Mock
    implements _i3.AuthenticationCredentialsRepository {
  MockAuthenticationCredentialsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> checkEmailAvailability(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkEmailAvailability,
          [email],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #checkEmailAvailability,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>>
      checkIfEmailIsAssociatedWithAnAccount(String? email) =>
          (super.noSuchMethod(
            Invocation.method(
              #checkIfEmailIsAssociatedWithAnAccount,
              [email],
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
                _FakeEither_0<_i5.Failure, bool>(
              this,
              Invocation.method(
                #checkIfEmailIsAssociatedWithAnAccount,
                [email],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> signInUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInUser,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #signInUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> signOutUser(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #signOutUser,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #signOutUser,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}
